### ISSUE TITLE
Multiple labels per plot task

### ISSUE THREAD

**Issue by MirjamSchr** [tillbiskup/aspecd#3]
When creating more than one figure with one plot task (e.g. with applying a SinglePlotter to multiple datasets), only one label (default: fig1/figx) can be set/is written in the history. 

To being able to include all figures in a composite plot, a label/result for every single plot needs to be created/taken from the input recipe.

**Comment by tillbiskup** [comment]
Generally, this should only be an issue with SinglePlot tasks, as a MultiPlot task with multiple datasets results in all datasets plotted into one plotter.

There is a difference between label and result, and only the label  is set automatically if not explicitly provided, but never the result.

As far as I can see, for a SinglePlot task, we would need to have the possibility to explicitly provide as many results (and labels) as there are datasets, to be able to explicitly refer to the individual plots. Each result should refer to the plotter applied to just *one* dataset.

A recipe may look like:

    - kind: singleplot
      type: SinglePlotter1D
      apply_to:
        - dataset1
        - dataset2
      result: 
        - 1D_plot_1
        - 1D_plot_2

Of course, the length of the `result` list would need to be as long as the list of the `apply_to` list.

Labels should automatically be added for each individual dataset as well, as applying a SinglePlotter to multiple datasets results in multiple figures. Here, the suggestion would be to extend the current scheme `fig#` with something like `fig#-#`.
