### ISSUE TITLE
Discussion on how to handle multidimensional data input from text files

### ISSUE THREAD

**Issue by MirjamSchr** [tillbiskup/aspecd#6]
Txt-files are currently imported ignoring a possible axis column except if exactly 2 columns are present.  In all other cases, the data is taken as is and put in the dataset as data. This is inconvenient, as a file with an axis column  and two or more data columns cannot be handled at the moment. 

It might be  worth, either introducing a parameter to set a/the first column as axis values, or to automatically read in the first column as axis values.

**Comment by tillbiskup** [comment]
I would opt for the additional parameter - name to be decided.
Furthermore, we would need to discuss whether the current implementation (in case of exactly two columns, use the first as axis) is still sensible/a good default. Perhaps having an additional axis parameter that can be set to ``None`` for not having any axis values would be an option here. This would allow to import txt data with two columns where both are data, and none axis values.
